"""Vectorizes the line-art source into `src/shared/ui/blueprint/lineart.ts`.

The source (`source.png`) is an image-model redraw of the signature outfit
as black line art. Requirements: potrace, Pillow, svgpathtools.

    python3 frontend/scripts/lineart/vectorize.py
"""

import argparse
import json
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image, ImageOps
from svgpathtools import parse_path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'src' / 'shared' / 'ui' / 'blueprint' / 'lineart.ts'
FIGURE_WIDTH = 400
TRACE_WIDTH = FIGURE_WIDTH * 2
PAD = 6


def fmt(value: float) -> str:
    text = f'{value:.1f}'
    return text[:-2] if text.endswith('.0') else text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=HERE / 'source.png')
    parser.add_argument('--output', type=Path, default=OUT)
    parser.add_argument('--height', type=float, help='Normalize a turnaround view to the front figure height.')
    parser.add_argument('--threshold', type=int, default=165, help='Ink threshold; higher includes lighter strokes.')
    parser.add_argument('--svg-output', type=Path, help='Also write a standalone SVG with the same coordinates.')
    args = parser.parse_args()
    source_image = Image.open(args.source).convert('RGBA')
    paper = Image.new('RGBA', source_image.size, 'white')
    image = Image.alpha_composite(paper, source_image).convert('L')
    box = ImageOps.invert(image.point(lambda v: 0 if v < 150 else 255)).getbbox()
    box = (box[0] - PAD, box[1] - PAD, box[2] + PAD, box[3] + PAD)
    crop = image.crop(box)
    trace_width = TRACE_WIDTH if args.height is None else round(crop.width * args.height * 2 / crop.height)
    height = round(crop.height * trace_width / crop.width)
    bitmap = crop.resize((trace_width, height), Image.LANCZOS).point(lambda v: 0 if v < args.threshold else 255).convert('1')

    with tempfile.TemporaryDirectory() as tmp:
        pbm, svg = Path(tmp) / 'in.pbm', Path(tmp) / 'out.svg'
        bitmap.save(pbm)
        subprocess.run(
            ['potrace', str(pbm), '-s', '-o', str(svg), '--turdsize', '4', '--alphamax', '1.1', '--opttolerance', '0.6', '-u', '1'],
            check=True,
        )
        source = svg.read_text()

    scale = FIGURE_WIDTH / TRACE_WIDTH
    offset_x = (FIGURE_WIDTH - trace_width * scale) / 2
    paths = []
    for d in re.findall(r'<path d="([^"]+)"', source, re.S):
        path = parse_path(d.replace('\n', ' ')).scaled(scale, -scale).translated(complex(offset_x, height * scale))
        commands = []
        for sub in path.continuous_subpaths():
            start = sub[0].start
            commands.append(f'M{fmt(start.real)} {fmt(start.imag)}')
            for seg in sub:
                if type(seg).__name__ == 'CubicBezier':
                    commands.append(
                        f'C{fmt(seg.control1.real)} {fmt(seg.control1.imag)} {fmt(seg.control2.real)} '
                        f'{fmt(seg.control2.imag)} {fmt(seg.end.real)} {fmt(seg.end.imag)}'
                    )
                else:
                    commands.append(f'L{fmt(seg.end.real)} {fmt(seg.end.imag)}')
            commands.append('Z')
        paths.append((path.bbox()[2], ''.join(commands)))
    paths.sort(key=lambda item: item[0])

    body = ',\n'.join(f'  {json.dumps(d)}' for _, d in paths)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        '// Generated by frontend/scripts/lineart/vectorize.py. Do not edit by hand.\n'
        f'export const LINEART_HEIGHT = {fmt(height * scale)};\n\n'
        '/** Filled potrace outlines of the line art, top to bottom. */\n'
        f'export const LINEART_PATHS: readonly string[] = [\n{body},\n];\n'
    )
    if args.svg_output:
        args.svg_output.parent.mkdir(parents=True, exist_ok=True)
        svg_paths = ''.join(f'<path d="{d}"/>' for _, d in paths)
        args.svg_output.write_text(
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {FIGURE_WIDTH} {fmt(height * scale)}">'
            f'<g fill="currentColor">{svg_paths}</g></svg>\n'
        )
    print(f'wrote {args.output} ({len(paths)} paths, width {fmt(trace_width * scale)}, height {fmt(height * scale)})')


if __name__ == '__main__':
    main()
