"""Vectorizes the line-art source into `src/shared/ui/blueprint/lineart.ts`.

The source (`source.png`) is an image-model redraw of the signature outfit
as black line art. Requirements: potrace, Pillow, svgpathtools.

    python3 frontend/scripts/lineart/vectorize.py
"""

import json
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image, ImageOps
from svgpathtools import parse_path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'src' / 'shared' / 'ui' / 'blueprint' / 'lineart.ts'
FIGURE_WIDTH = 400
TRACE_WIDTH = FIGURE_WIDTH * 2
PAD = 6


def fmt(value: float) -> str:
    text = f'{value:.1f}'
    return text[:-2] if text.endswith('.0') else text


def main() -> None:
    image = Image.open(HERE / 'source.png').convert('L')
    box = ImageOps.invert(image.point(lambda v: 0 if v < 150 else 255)).getbbox()
    box = (box[0] - PAD, box[1] - PAD, box[2] + PAD, box[3] + PAD)
    crop = image.crop(box)
    height = round(crop.height * TRACE_WIDTH / crop.width)
    bitmap = crop.resize((TRACE_WIDTH, height), Image.LANCZOS).point(lambda v: 0 if v < 165 else 255).convert('1')

    with tempfile.TemporaryDirectory() as tmp:
        pbm, svg = Path(tmp) / 'in.pbm', Path(tmp) / 'out.svg'
        bitmap.save(pbm)
        subprocess.run(
            ['potrace', str(pbm), '-s', '-o', str(svg), '--turdsize', '4', '--alphamax', '1.1', '--opttolerance', '0.6', '-u', '1'],
            check=True,
        )
        source = svg.read_text()

    scale = FIGURE_WIDTH / TRACE_WIDTH
    paths = []
    for d in re.findall(r'<path d="([^"]+)"', source, re.S):
        path = parse_path(d.replace('\n', ' ')).scaled(scale, -scale).translated(complex(0, height * scale))
        commands = []
        for sub in path.continuous_subpaths():
            start = sub[0].start
            commands.append(f'M{fmt(start.real)} {fmt(start.imag)}')
            for seg in sub:
                if type(seg).__name__ == 'CubicBezier':
                    commands.append(
                        f'C{fmt(seg.control1.real)} {fmt(seg.control1.imag)} {fmt(seg.control2.real)} '
                        f'{fmt(seg.control2.imag)} {fmt(seg.end.real)} {fmt(seg.end.imag)}'
                    )
                else:
                    commands.append(f'L{fmt(seg.end.real)} {fmt(seg.end.imag)}')
            commands.append('Z')
        paths.append((path.bbox()[2], ''.join(commands)))
    paths.sort(key=lambda item: item[0])

    body = ',\n'.join(f'  {json.dumps(d)}' for _, d in paths)
    OUT.write_text(
        '// Generated by frontend/scripts/lineart/vectorize.py. Do not edit by hand.\n'
        f'export const LINEART_HEIGHT = {fmt(height * scale)};\n\n'
        '/** Filled potrace outlines of the line art, top to bottom. */\n'
        f'export const LINEART_PATHS: readonly string[] = [\n{body},\n];\n'
    )
    print(f'wrote {OUT} ({len(paths)} paths)')


if __name__ == '__main__':
    main()
