/**
 * Canonical character record. Edited by hand; validated by the domain when
 * the repository loads it.
 */
export const characterContent = {
  name: 'Lynn',
  tagline: 'A quiet observer drawn in navy ink and silver-white.',
  summary:
    'Lynn is the original character of Steven Lynn. She started as a personal avatar, went through several redesigns, and settled into her silver-haired form. This site is her standard: what never changes, what may, and how she is used in interfaces, stickers and music videos.',
  credits: [
    { role: 'Creator', name: 'Steven Lynn', url: 'https://x.com/Stv_Lynn' },
    { role: 'Sticker set', name: 'Lynn-chan Stickers', url: 'https://github.com/stvlynn/sticker' },
  ],
  facts: [
    { label: 'Designation', value: 'Original character' },
    { label: 'Canonical look', value: 'OF-01 · Signature' },
    { label: 'Proportion', value: '6.6 heads' },
    { label: 'Accent', value: 'Cornflower ribbon' },
    { label: 'Temperament', value: 'Quiet, curious, deadpan' },
    { label: 'Habitat', value: 'Rainy commutes, late studios' },
  ],
  pillars: [
    {
      id: 'quiet-first',
      title: 'Quiet first',
      body: 'Lynn is rarely the loudest thing in a frame. Crowds blur, rooms fall apart, papers fly — she stays still and in focus. Compose around her calm, not her pose.',
    },
    {
      id: 'ink-and-paper',
      title: 'Ink and paper',
      body: 'Navy ink for weight, silver-white paper for light, one cornflower ribbon for color. Anything louder has to earn its place in the frame.',
    },
    {
      id: 'dreams-with-a-ruler',
      title: 'Dreams with a ruler',
      body: 'Her worlds are surreal — inverted skylines, floating blocks, a typewriter that prints smiles — but always built from clean geometry and flat, even light.',
    },
    {
      id: 'shared-by-hand',
      title: 'Shared by hand',
      body: 'Stickers, covers and illustrations are made to be passed around. Credit the author, keep the identity intact, and keep it non-commercial.',
    },
  ],
  traits: [
    {
      id: 'beret',
      part: 'Headwear',
      label: 'Black beret',
      detail: 'Soft wool, worn tilted back so the bangs show.',
      swatch: { label: 'Beret', token: '--lynn-beret' },
    },
    {
      id: 'ribbon',
      part: 'Headwear',
      label: 'Cornflower ribbon',
      detail: 'A bow at the back right of the beret. The brand accent.',
      swatch: { label: 'Ribbon', token: '--lynn-ribbon' },
    },
    {
      id: 'hair',
      part: 'Hair',
      label: 'Silver-white bob',
      detail: 'Chin length, blunt bangs split over the left eye.',
      swatch: { label: 'Hair', token: '--lynn-hair' },
    },
    {
      id: 'hair-tips',
      part: 'Hair',
      label: 'Cyan inner tips',
      detail: 'Only the underside of the ends. Never a full-head dye.',
      swatch: { label: 'Tip', token: '--lynn-tip' },
    },
    {
      id: 'hair-clip',
      part: 'Hair',
      label: 'Cyan hair clip',
      detail: 'A slim clip on the right bangs, sometimes paired.',
      swatch: null,
    },
    {
      id: 'glasses',
      part: 'Face',
      label: 'Round gold glasses',
      detail: 'Thin wire, perfectly round lenses, sitting slightly low.',
      swatch: { label: 'Glasses', token: '--lynn-glasses' },
    },
    {
      id: 'eyes',
      part: 'Face',
      label: 'Light blue eyes',
      detail: 'Large irises with a pale lower highlight.',
      swatch: { label: 'Iris', token: '--lynn-iris' },
    },
    {
      id: 'collar',
      part: 'Blouse',
      label: 'Sailor collar',
      detail: 'White collar edged with a light-blue piping line.',
      swatch: null,
    },
    {
      id: 'bow',
      part: 'Blouse',
      label: 'Cyan bow',
      detail: 'Ribbon bow at the collar with two long tails.',
      swatch: { label: 'Bow', token: '--lynn-bow' },
    },
    {
      id: 'name-bar',
      part: 'Blouse',
      label: 'Name bar',
      detail: 'A small blue bar above the left chest pocket line.',
      swatch: { label: 'Name bar', token: '--lynn-name-bar' },
    },
    {
      id: 'clasps',
      part: 'Skirt',
      label: 'Orbit clasps',
      detail: 'Two silver ring-and-orbit clasps on the high waistband.',
      swatch: null,
    },
    {
      id: 'skirt',
      part: 'Skirt',
      label: 'Navy pleated skirt',
      detail: 'High-waisted, knife pleats, above the knee.',
      swatch: { label: 'Skirt', token: '--lynn-skirt' },
    },
    {
      id: 'socks',
      part: 'Feet',
      label: 'White socks',
      detail: 'Ankle length, slightly slouched.',
      swatch: null,
    },
    {
      id: 'loafers',
      part: 'Feet',
      label: 'Black loafers',
      detail: 'Penny loafers with a low block heel.',
      swatch: { label: 'Loafer', token: '--lynn-loafer' },
    },
  ],
  palette: [
    { label: 'Hair', token: '--lynn-hair' },
    { label: 'Hair shade', token: '--lynn-hair-shade' },
    { label: 'Tip', token: '--lynn-tip' },
    { label: 'Iris', token: '--lynn-iris' },
    { label: 'Bow', token: '--lynn-bow' },
    { label: 'Ribbon', token: '--lynn-ribbon' },
    { label: 'Beret', token: '--lynn-beret' },
    { label: 'Skirt', token: '--lynn-skirt' },
    { label: 'Glasses', token: '--lynn-glasses' },
    { label: 'Skin', token: '--lynn-skin' },
  ],
  proportion: {
    headsTall: 6.6,
    note: 'One head unit runs from the crown of the skull to the chin; the beret is excluded. Chibi stickers compress her to about 2.5 heads.',
  },
  referenceSheet: {
    src: '/media/reference/original-sheet.webp',
    width: 1300,
    height: 1975,
    alt: 'Original full-body reference of Lynn in the signature beret uniform, touching her lip mid-step.',
  },
  doNot: [
    'No long, curled or tied-up hair. The bob always ends at the chin.',
    'No square, rimless or thick-framed glasses.',
    'No full-head cyan. The color lives only on the inner tips.',
    'No face marks, cheek hearts or tattoos.',
    'No ribbon on the front of the beret.',
    'No black skirt. It is navy, and it keeps its two clasps.',
  ],
} as const;
