export const artworkContent = [
  {
    id: 'crowd-in-the-rain',
    code: 'AR-01',
    title: 'Crowd in the Rain',
    caption: 'Commuters smear into motion blur under grey umbrellas. Lynn is the only figure drawn sharp and still.',
    mood: 'Solitary · hushed',
    image: {
      src: '/media/artworks/crowd-in-the-rain.webp',
      width: 768,
      height: 1376,
      alt: 'Lynn in profile, face hidden by her bangs, standing in a blurred crowd of umbrellas in the rain.',
    },
    palette: [
      { label: 'Slate', hex: '#46526d' },
      { label: 'Umbrella', hex: '#7e89a4' },
      { label: 'Mist', hex: '#cdceda' },
      { label: 'Paper', hex: '#e6e4e9' },
    ],
    motifs: ['Rain', 'Motion blur', 'Profile', 'Umbrellas'],
  },
  {
    id: 'falling-studio',
    code: 'AR-02',
    title: 'Falling Studio',
    caption:
      'An artist’s room comes apart mid-air: letters, a phone, an hourglass, a can of red paint. A primary-color grid hides her face.',
    mood: 'Dreamlike · restless',
    image: {
      src: '/media/artworks/falling-studio.webp',
      width: 851,
      height: 1400,
      alt: 'Lynn falling through a room of floating papers, monitors and flowers, her face covered by a red, yellow and blue grid painting.',
    },
    palette: [
      { label: 'Night', hex: '#2b3351' },
      { label: 'Indigo', hex: '#404368' },
      { label: 'Violet', hex: '#575d88' },
      { label: 'Heather', hex: '#938aa8' },
      { label: 'Rose', hex: '#b8a2b2' },
    ],
    motifs: ['Paper', 'Hourglass', 'CRT', 'Primary grid', 'Palette'],
  },
  {
    id: 'typewriter-city',
    code: 'AR-03',
    title: 'Typewriter City',
    caption: 'She types a long ribbon of smiles into a dusk sky full of floating blocks and a far-off spire.',
    mood: 'Wistful · warm',
    image: {
      src: '/media/artworks/typewriter-city.webp',
      width: 933,
      height: 1400,
      alt: 'Lynn seen from behind at a typewriter, a paper ribbon of smiley faces rising toward a pink and violet floating city.',
    },
    palette: [
      { label: 'Night', hex: '#2a314d' },
      { label: 'Twilight', hex: '#3f476e' },
      { label: 'Lavender', hex: '#7c78a9' },
      { label: 'Mauve', hex: '#b49aba' },
      { label: 'Dusk', hex: '#e6beb7' },
    ],
    motifs: ['Typewriter', 'Voxel city', 'Crescent moon', 'Telephone'],
  },
  {
    id: 'inverted-skyline',
    code: 'AR-04',
    title: 'Inverted Skyline',
    caption: 'Sitting on a beam between two mirrored cities. Papers drift upward; a single chair waits in a doorway.',
    mood: 'Suspended · calm',
    image: {
      src: '/media/artworks/inverted-skyline.webp',
      width: 933,
      height: 1400,
      alt: 'Lynn in a dark coat sitting on a concrete beam between an upright and an upside-down city at dusk.',
    },
    palette: [
      { label: 'Night', hex: '#323b56' },
      { label: 'Concrete', hex: '#485376' },
      { label: 'Haze', hex: '#71799f' },
      { label: 'Lilac', hex: '#bbb2c9' },
      { label: 'Blush', hex: '#e4c8ca' },
    ],
    motifs: ['Mirrored city', 'Loose paper', 'Empty chair', 'Low sun'],
  },
] as const;
