/** Sticker catalog, mirrored from github.com/stvlynn/sticker. */
export const stickerContent: readonly (readonly [id: string, title: string, kind: 'caption' | 'expression'])[] = [
  ['st-001', '007', 'caption'],
  ['st-002', '8000', 'caption'],
  ['st-003', 'AI生成', 'caption'],
  ['st-004', 'OB', 'caption'],
  ['st-005', 'allin', 'caption'],
  ['st-006', 'attention', 'caption'],
  ['st-007', 'chatgpt', 'caption'],
  ['st-008', 'claude', 'caption'],
  ['st-009', 'ddl', 'caption'],
  ['st-010', 'dify', 'caption'],
  ['st-011', 'gal', 'caption'],
  ['st-012', 'idea', 'caption'],
  ['st-013', 'itworks', 'caption'],
  ['st-014', 'llama', 'caption'],
  ['st-015', 'mhy', 'caption'],
  ['st-016', 'outofmemory', 'caption'],
  ['st-017', 'prompt大师', 'caption'],
  ['st-018', 'sota', 'caption'],
  ['st-019', 'tcdw', 'caption'],
  ['st-020', 'token不足', 'caption'],
  ['st-021', 'urright', 'caption'],
  ['st-022', 'vibeweave', 'caption'],
  ['st-023', 'zeroshot', 'caption'],
  ['st-024', '上下文过长', 'caption'],
  ['st-025', '不如麦当劳', 'caption'],
  ['st-026', '今天吃肉', 'caption'],
  ['st-027', '全干工程师', 'caption'],
  ['st-028', '准点下班', 'caption'],
  ['st-029', '加载中', 'caption'],
  ['st-030', '压抑', 'caption'],
  ['st-031', '又亏了', 'caption'],
  ['st-032', '吃惊', 'caption'],
  ['st-033', '咖啡', 'caption'],
  ['st-034', '在忙', 'caption'],
  ['st-035', '对齐', 'caption'],
  ['st-036', '干饭', 'caption'],
  ['st-037', '幻觉', 'caption'],
  ['st-038', '开会中', 'caption'],
  ['st-039', '微调中', 'caption'],
  ['st-040', '怎么改', 'caption'],
  ['st-041', '怒了', 'caption'],
  ['st-042', '思考', 'caption'],
  ['st-043', '愤怒', 'caption'],
  ['st-044', '打call', 'caption'],
  ['st-045', '打工人', 'caption'],
  ['st-046', '打边炉', 'caption'],
  ['st-047', '技术调整', 'caption'],
  ['st-048', '抄底成功', 'caption'],
  ['st-049', '推理完成', 'caption'],
  ['st-050', '摸鱼', 'caption'],
  ['st-051', '晚安', 'caption'],
  ['st-052', '服务器炸了', 'caption'],
  ['st-053', '梭哈', 'caption'],
  ['st-054', '求打赏', 'caption'],
  ['st-055', '画大饼', 'caption'],
  ['st-056', '疯狂星期六', 'caption'],
  ['st-057', '稳如老狗', 'caption'],
  ['st-058', '贴贴', 'caption'],
  ['st-059', '跌', 'caption'],
  ['st-060', '连接失败', 'caption'],
  ['st-061', '需求多', 'caption'],
  ['st-062', '项目上线', 'caption'],
  ['st-063', '饮茶', 'caption'],
  ['st-064', '饿饿饭饭', 'caption'],
  ['st-065', '黑暗料理', 'caption'],
  ['st-066', 'angry', 'expression'],
  ['st-067', 'angry_veins', 'expression'],
  ['st-068', 'bubble_tea', 'expression'],
  ['st-069', 'coffee_desperate', 'expression'],
  ['st-070', 'confused', 'expression'],
  ['st-071', 'deadpan', 'expression'],
  ['st-072', 'detective', 'expression'],
  ['st-073', 'evil_grin', 'expression'],
  ['st-074', 'its_fire', 'expression'],
  ['st-075', 'loading', 'expression'],
  ['st-076', 'monster', 'expression'],
  ['st-077', 'ok_hand', 'expression'],
  ['st-078', 'orange', 'expression'],
  ['st-079', 'yandere_knife', 'expression'],
];

export const stickerGuideContent = {
  summary: 'Chibi Lynn for chat. A big head, one clear pose and at most one short caption, readable at thumbnail size.',
  canvas: {
    width: 512,
    height: 512,
    format: 'PNG · RGBA',
    background: { label: 'Generation field · RGB(240, 240, 240)', hex: '#f0f0f0' },
    outline: 'White stroke, 8–12 px, around the figure and the caption',
    safeArea: 24,
  },
  rules: [
    {
      id: 'one-idea',
      title: 'One idea per sticker',
      body: 'One emotion or one joke. If it needs two captions, it is two stickers.',
      verdict: 'do',
    },
    {
      id: 'thumbnail',
      title: 'Readable at 128 px',
      body: 'Check the silhouette and caption at chat size before publishing. Thick shapes, big eyes, heavy caption weight.',
      verdict: 'do',
    },
    {
      id: 'outline',
      title: 'Always outline in white',
      body: 'The white stroke separates Lynn from dark and light chat themes alike. Props and small scenes sit inside it.',
      verdict: 'do',
    },
    {
      id: 'identity',
      title: 'Keep the identity',
      body: 'Beret, round glasses, silver bob with cyan tips and the blouse bow survive every deformation.',
      verdict: 'do',
    },
    {
      id: 'caption-language',
      title: 'Captions in Simplified Chinese',
      body: 'Short, spoken phrases. English is fine for product names and memes that are read in English.',
      verdict: 'note',
    },
    {
      id: 'caption-length',
      title: 'No captions over 12 characters',
      body: 'Longer text shrinks below legibility. Cut the phrase, or let the pose carry it.',
      verdict: 'dont',
    },
    {
      id: 'crop',
      title: 'Don’t crop the beret',
      body: 'The beret and ribbon are the fastest way to recognize her at a glance. Keep them inside the safe area.',
      verdict: 'dont',
    },
    {
      id: 'script-fonts',
      title: 'No thin or script lettering',
      body: 'Use a heavy rounded sans for captions. Hairline and handwriting styles vanish at chat size.',
      verdict: 'dont',
    },
  ],
  promptTemplate:
    '将角色变形并设计一张 LINE 贴纸。姿势和文字排版要富有创意，变化丰富，设计独特。对话应为简体中文，参考 sticker 示例。使用文本"{text}"，动作是{action}。图片整体使用浅灰色 RGB(240, 240, 240) 背景，文字和角色周围有白色描边。',
  promptExample: { text: '干饭', action: '开心地吃饭' },
  license:
    'CC BY 4.0 with attribution to the original author. The author asks that the stickers are not used commercially.',
  channels: [
    { name: 'Telegram', url: 'https://t.me/addstickers/lynnchan' },
    { name: 'WeChat', url: 'https://w.url.cn/s/AhlJ5Bk' },
    { name: 'GitHub', url: 'https://github.com/stvlynn/sticker' },
  ],
} as const;
