const image = (id: string, width: number, alt: string) => ({
  src: `/media/outfits/${id}.webp`,
  width,
  height: 1400,
  alt,
});

export const outfitContent = [
  {
    id: 'signature',
    code: 'OF-01',
    name: 'Signature',
    occasion: 'Everyday · canonical',
    summary: 'The look every other outfit is measured against. When in doubt, draw this one.',
    canonical: true,
    image: image('signature', 401, 'Lynn standing with her hands behind her back in the beret uniform.'),
    garments: [
      { slot: 'Headwear', name: 'Black beret, cornflower ribbon at the back' },
      { slot: 'Top', name: 'White long-sleeved sailor blouse with light-blue piping' },
      { slot: 'Neck', name: 'Cyan ribbon bow' },
      { slot: 'Detail', name: 'Blue name bar on the chest' },
      { slot: 'Bottom', name: 'High-waisted navy pleated skirt, two orbit clasps' },
      { slot: 'Feet', name: 'White ankle socks, black penny loafers' },
    ],
    palette: [
      { label: 'Beret', token: '--lynn-beret' },
      { label: 'Blouse', hex: '#f4f6fa' },
      { label: 'Bow', token: '--lynn-bow' },
      { label: 'Skirt', token: '--lynn-skirt' },
    ],
    source: 'Reference sheet by YAYOI の 夢',
  },
  {
    id: 'magician',
    code: 'OF-02',
    name: 'Magician',
    occasion: 'Stage · PV costume A',
    summary: 'The performer role from the Trick Heart PV. Locked for every shot of that production.',
    canonical: false,
    image: image('magician', 510, 'Lynn in a top hat and navy tailcoat, presenting a playing card.'),
    garments: [
      { slot: 'Headwear', name: 'Diamond-patterned black top hat, cyan band' },
      { slot: 'Top', name: 'Navy fitted tailcoat with cyan cuffs, white shirt' },
      { slot: 'Neck', name: 'Cyan bow tie' },
      { slot: 'Hands', name: 'White gloves' },
      { slot: 'Bottom', name: 'Black shorts' },
      { slot: 'Feet', name: 'Black-and-white striped stockings, navy boots' },
    ],
    palette: [
      { label: 'Tailcoat', hex: '#23305a' },
      { label: 'Cuff', token: '--lynn-tip' },
      { label: 'Glove', hex: '#f7f8fb' },
      { label: 'Hat', hex: '#1c2238' },
    ],
    source: 'Trick Heart PV · costume lock',
  },
  {
    id: 'rainy',
    code: 'OF-03',
    name: 'Rainy Commute',
    occasion: 'Winter term · grey mornings',
    summary: 'A navy-collared sailor uniform for crowds and rain. Carries a clear umbrella, rarely opens it.',
    canonical: false,
    image: image('rainy', 468, 'Lynn in a navy-collared sailor uniform holding a clear umbrella and a tote bag.'),
    garments: [
      { slot: 'Headwear', name: 'Navy beret, large cornflower bow' },
      { slot: 'Top', name: 'White blouse, navy sailor collar with two white stripes' },
      { slot: 'Neck', name: 'Cornflower sailor scarf' },
      { slot: 'Bottom', name: 'Navy pleated skirt' },
      { slot: 'Carry', name: 'Canvas tote, clear umbrella' },
      { slot: 'Feet', name: 'White knee socks, black loafers' },
    ],
    palette: [
      { label: 'Collar', token: '--ink-800' },
      { label: 'Scarf', token: '--corn-400' },
      { label: 'Blouse', token: '--ink-100' },
      { label: 'Rain', token: '--scene-rain' },
    ],
    source: 'Artwork AR-01 · Crowd in the Rain',
  },
  {
    id: 'night',
    code: 'OF-04',
    name: 'Night Walk',
    occasion: 'After dark · city edges',
    summary: 'An oversized duffle coat and sneakers for sitting on ledges above upside-down skylines.',
    canonical: false,
    image: image('night', 441, 'Lynn in an oversized navy duffle coat and white sneakers, hands in pockets.'),
    garments: [
      { slot: 'Headwear', name: 'Navy beret, cornflower bow' },
      { slot: 'Outer', name: 'Oversized hooded duffle coat, toggle buttons' },
      { slot: 'Bottom', name: 'Charcoal pleated mini skirt' },
      { slot: 'Carry', name: 'Small black crossbody bag' },
      { slot: 'Feet', name: 'White ribbed socks, chunky white sneakers' },
    ],
    palette: [
      { label: 'Coat', token: '--ink-900' },
      { label: 'Skirt', token: '--ink-700' },
      { label: 'Sneaker', token: '--ink-100' },
      { label: 'Dusk', token: '--scene-dusk' },
    ],
    source: 'Artwork AR-04 · Inverted Skyline',
  },
  {
    id: 'atelier',
    code: 'OF-05',
    name: 'Atelier',
    occasion: 'Painting days',
    summary: 'A cable-knit sweater and a white skirt that collects primary-color stains on purpose.',
    canonical: false,
    image: image('atelier', 564, 'Lynn in a navy sweater and paint-flecked white skirt holding a palette and brush.'),
    garments: [
      { slot: 'Headwear', name: 'Black beret, blue ribbon' },
      { slot: 'Top', name: 'Deep-navy cable-knit sweater, long sleeves' },
      { slot: 'Bottom', name: 'White A-line midi skirt with red, yellow and blue flecks' },
      { slot: 'Carry', name: 'Wooden palette, fine brush' },
      { slot: 'Feet', name: 'White socks, black loafers' },
    ],
    palette: [
      { label: 'Knit', hex: '#23305a' },
      { label: 'Red', hex: '#d33c32' },
      { label: 'Yellow', hex: '#f0c233' },
      { label: 'Blue', token: '--lynn-ribbon' },
    ],
    source: 'Artwork AR-02 · Falling Studio',
  },
  {
    id: 'studio',
    code: 'OF-06',
    name: 'Studio',
    occasion: 'Deep work · deploy nights',
    summary: 'The developer-life look of the sticker set: hoodie, headphones, laptop, coffee.',
    canonical: false,
    image: image('studio', 473, 'Lynn in an open grey hoodie with headphones around her neck, a laptop and a coffee.'),
    garments: [
      { slot: 'Headwear', name: 'Black beret, blue ribbon' },
      { slot: 'Outer', name: 'Oversized grey-blue zip hoodie' },
      { slot: 'Top', name: 'White T-shirt' },
      { slot: 'Bottom', name: 'Navy wide-leg trousers' },
      { slot: 'Carry', name: 'Cornflower headphones, laptop, takeaway coffee' },
      { slot: 'Feet', name: 'White sneakers' },
    ],
    palette: [
      { label: 'Hoodie', hex: '#c8cfdf' },
      { label: 'Headphones', token: '--corn-500' },
      { label: 'Trousers', token: '--ink-800' },
      { label: 'Coffee', hex: '#9b6b43' },
    ],
    source: 'Sticker set · developer life',
  },
] as const;
